Update API.
- API endpoints are moved to '/api/v0' instead of simply '/api'
- All responses where the request didn't result in an internal error are sent out with the following schema:

```json
{
    data: Any,
    error: { type: String, message: String }?,
    message: String?,
    meta: {
      api_version: String,
      timestamp: Number,
      status: Number,
      ...
    }
}
```